name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build packages for ${{ matrix.TARGET_FORMATTED }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: |
                pyinstaller --windowed -F -n stemplayer-explorer -D main.py
            OUT_FILE_NAME: stemplayer-explorer
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -n stemplayer-explorer -D main.py
            OUT_FILE_NAME: stemplayer-explorer
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: |
              sudo apt-get install python3 python3-dev xcb python3-pyqt5 pyqt5-dev pyqt5-dev-tools -y
              pyinstaller -F -n stemplayer-explorer -D main.py
            OUT_FILE_NAME: stemplayer-explorer

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Build with pyinstaller for ${{ matrix.TARGET }}
      run: |
        cd src
        ${{ matrix.CMD_BUILD }} 
        chmod +x dist/stemplayer-explorer/${{ matrix.OUT_FILE_NAME }}
    - uses: actions/upload-artifact@v2
      with:
        name: stemplayer-explorer-${{ matrix.TARGET }}
        path: src/dist/${{ matrix.OUT_FILE_NAME }}

    # - name: Load Release URL File from release job
    #   uses: actions/download-artifact@v1
    #   with:
    #     name: release_url

    # - name: Get Release File Name & Upload URL
    #   id: get_release_info
    #   shell: bash
    #   run: |
    #     value=`cat release_url/release_url.txt`
    #     echo ::set-output name=upload_url::$value
